export const INIT_TEACHERS = [
  {
    id: 1,
    name: "Prof. Shwetha",
    email: "shwetha@college.edu",
    password: "shwetha@123",
    department: "CSE",
    subjects: ["Computer Networks", "Computer Networks Lab"],
    phone: "9876540001"
  },
  {
    id: 2,
    name: "Prof. Anuradha",
    email: "anuradha@college.edu",
    password: "anuradha@123",
    department: "CSE",
    subjects: ["Software Development Life Cycle"],
    phone: "9876540002"
  },
  {
    id: 3,
    name: "Prof. Hema",
    email: "hema@college.edu",
    password: "hema@123",
    department: "CSE",
    subjects: ["Artificial Intelligence"],
    phone: "9876540003"
  },
  {
    id: 4,
    name: "Prof. Vaishnavi",
    email: "vaishnavi@college.edu",
    password: "vaishnavi@123",
    department: "CSE",
    subjects: ["Parallel Computing", "Parallel Computing Lab"],
    phone: "9876540004"
  },
  {
    id: 5,
    name: "Prof. Anitha",
    email: "anitha@college.edu",
    password: "anitha@123",
    department: "CSE",
    subjects: ["Database Management System", "DBMS Lab"],
    phone: "9876540005"
  },
];

export const INIT_STUDENTS = [
  {
    id: 1,
    usn: "1SG22CS108",
    name: "Sudarshan",
    email: "sudarshan@student.edu",
    password: "student123",
    phone: "9876543201",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "AI/ML",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.9,
    cgpa: 8.7,
    backlogs: 0,
    status: "approved",
    teacherId: 1,
    attendance: { "Computer Networks": 85, "Computer Networks Lab": 80 },
    sgpaHist: [8.1, 8.3, 8.5, 8.6, 8.7, 8.8, 8.9, 8.9],
    notifications: [
      { id: 1, msg: "Profile approved by Prof. Shwetha", type: "success", read: false, date: "Dec 01" }
    ]
  },
  {
    id: 2,
    usn: "1SG22CS109",
    name: "Srujan",
    email: "srujan@student.edu",
    password: "student123",
    phone: "9876543202",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Web Development",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 9.1,
    cgpa: 9.0,
    backlogs: 0,
    status: "approved",
    teacherId: 1,
    attendance: { "Computer Networks": 90, "Computer Networks Lab": 88 },
    sgpaHist: [8.5, 8.7, 8.8, 8.9, 9.0, 9.0, 9.1, 9.1],
    notifications: []
  },
  {
    id: 3,
    usn: "1SG22CS087",
    name: "Sangamesh",
    email: "sangamesh@student.edu",
    password: "student123",
    phone: "9876543203",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Cybersecurity",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.0,
    cgpa: 8.0,
    backlogs: 0,
    status: "approved",
    teacherId: 1,
    attendance: { "Computer Networks": 89, "Computer Networks Lab": 95 },
    sgpaHist: [8.0, 8.0, 8.0, 8.2, 7.8, 8.1, 7.9, 8.0],
    notifications: [
      { id: 1, msg: "Computer Networks Lab attendance below 75% — warning issued", type: "warn", read: false, date: "Dec 03" }
    ]
  },
  {
    id: 4,
    usn: "1SG22CS109",
    name: "Sudeep",
    email: "sudeep@student.edu",
    password: "student123",
    phone: "9876543204",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Cloud Computing",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.4,
    cgpa: 8.2,
    backlogs: 0,
    status: "approved",
    teacherId: 1,
    attendance: { "Computer Networks": 88, "Computer Networks Lab": 84 },
    sgpaHist: [7.8, 8.0, 8.1, 8.1, 8.2, 8.2, 8.3, 8.4],
    notifications: []
  },
  {
    id: 5,
    usn: "1SG22CS065",
    name: "Niteesh",
    email: "niteesh@student.edu",
    password: "student123",
    phone: "9876543205",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Data Science",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 9.3,
    cgpa: 9.1,
    backlogs: 0,
    status: "approved",
    teacherId: 1,
    attendance: { "Computer Networks": 92, "Computer Networks Lab": 90 },
    sgpaHist: [8.7, 8.9, 9.0, 9.0, 9.1, 9.1, 9.2, 9.3],
    notifications: []
  },
  {
    id: 6,
    usn: "1SG22CS113",
    name: "Rakshitha",
    email: "rakshitha@student.edu",
    password: "student123",
    phone: "9876543206",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Machine Learning",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.6,
    cgpa: 8.4,
    backlogs: 0,
    status: "approved",
    teacherId: 2,
    attendance: { "Software Development Life Cycle": 86 },
    sgpaHist: [7.9, 8.1, 8.2, 8.3, 8.3, 8.4, 8.5, 8.6],
    notifications: []
  },
  {
    id: 7,
    usn: "1SG22CS114",
    name: "Sneha",
    email: "Sneha@student.edu",
    password: "student123",
    phone: "9876543207",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "IoT",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 7.5,
    cgpa: 7.3,
    backlogs: 1,
    status: "approved",
    teacherId: 2,
    attendance: { "Software Development Life Cycle": 72 },
    sgpaHist: [6.8, 7.0, 7.1, 7.2, 7.2, 7.3, 7.4, 7.5],
    notifications: [
      { id: 1, msg: "SDLC attendance below 75% — warning issued", type: "warn", read: false, date: "Dec 02" }
    ]
  },
  {
    id: 8,
    usn: "1SG22CS115",
    name: "Sahana",
    email: "sahanaa@student.edu",
    password: "student123",
    phone: "9876543208",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "DevOps",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.0,
    cgpa: 7.8,
    backlogs: 0,
    status: "approved",
    teacherId: 2,
    attendance: { "Software Development Life Cycle": 80 },
    sgpaHist: [7.2, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0],
    notifications: []
  },
  {
    id: 9,
    usn: "1SG22CS116",
    name: "Santhosh",
    email: "Santhosh@student.edu",
    password: "student123",
    phone: "9876543209",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Blockchain",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 9.4,
    cgpa: 9.2,
    backlogs: 0,
    status: "pending",
    teacherId: 2,
    attendance: {},
    sgpaHist: [8.8, 9.0, 9.1, 9.2, 9.2, 9.3, 9.4, 9.4],
    notifications: [
      { id: 1, msg: "Your profile is pending teacher approval", type: "info", read: false, date: "Dec 05" }
    ]
  },
  {
    id: 10,
    usn: "1SG22CS117",
    name: "Spoorthi",
    email: "Spoorthi@student.edu",
    password: "student123",
    phone: "9876543210",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "AR/VR",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.2,
    cgpa: 8.0,
    backlogs: 0,
    status: "approved",
    teacherId: 3,
    attendance: { "Artificial Intelligence": 83 },
    sgpaHist: [7.5, 7.7, 7.8, 7.9, 8.0, 8.0, 8.1, 8.2],
    notifications: []
  },
  {
    id: 11,
    usn: "1SG22CS118",
    name: "Pankaj",
    email: "Pankaj@student.edu",
    password: "student123",
    phone: "9876543211",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Robotics",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 7.6,
    cgpa: 7.4,
    backlogs: 1,
    status: "approved",
    teacherId: 3,
    attendance: { "Artificial Intelligence": 68 },
    sgpaHist: [6.9, 7.1, 7.2, 7.3, 7.3, 7.4, 7.5, 7.6],
    notifications: [
      { id: 1, msg: "Artificial Intelligence attendance critically low (68%)", type: "danger", read: false, date: "Dec 04" }
    ]
  },
  {
    id: 12,
    usn: "1SG22CS119",
    name: "Preethi",
    email: "preethi@student.edu",
    password: "student123",
    phone: "9876543212",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "AI/ML",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.7,
    cgpa: 8.5,
    backlogs: 0,
    status: "approved",
    teacherId: 3,
    attendance: { "Artificial Intelligence": 91 },
    sgpaHist: [8.0, 8.2, 8.3, 8.4, 8.4, 8.5, 8.6, 8.7],
    notifications: []
  },
  {
    id: 13,
    usn: "1SG22CS120",
    name: "Saurav",
    email: "saurav@student.edu",
    password: "student123",
    phone: "9876543213",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Data Science",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 7.9,
    cgpa: 7.7,
    backlogs: 0,
    status: "approved",
    teacherId: 4,
    attendance: { "Parallel Computing": 78, "Parallel Computing Lab": 75 },
    sgpaHist: [7.2, 7.4, 7.5, 7.6, 7.6, 7.7, 7.8, 7.9],
    notifications: []
  },
  {
    id: 14,
    usn: "1SG22CS121",
    name: "Savitha",
    email: "savitha@student.edu",
    password: "student123",
    phone: "9876543214",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Cloud Computing",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.3,
    cgpa: 8.1,
    backlogs: 0,
    status: "approved",
    teacherId: 4,
    attendance: { "Parallel Computing": 84, "Parallel Computing Lab": 80 },
    sgpaHist: [7.6, 7.8, 7.9, 8.0, 8.0, 8.1, 8.2, 8.3],
    notifications: []
  },
  {
    id: 15,
    usn: "1SG22CS122",
    name: "Lakshmi",
    email: "lakshmi@student.edu",
    password: "student123",
    phone: "9876543215",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Web Development",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 6.8,
    cgpa: 6.6,
    backlogs: 2,
    status: "approved",
    teacherId: 4,
    attendance: { "Parallel Computing": 62, "Parallel Computing Lab": 58 },
    sgpaHist: [6.0, 6.2, 6.3, 6.4, 6.5, 6.5, 6.6, 6.8],
    notifications: [
      { id: 1, msg: "Parallel Computing Lab attendance critical (58%) — academic warning", type: "danger", read: false, date: "Dec 01" }
    ]
  },
  {
    id: 16,
    usn: "1SG22CS123",
    name: "Saransh",
    email: "Saransh@student.edu",
    password: "student123",
    phone: "9876543216",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Cybersecurity",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 9.0,
    cgpa: 8.8,
    backlogs: 0,
    status: "approved",
    teacherId: 5,
    attendance: { "Database Management System": 93, "DBMS Lab": 90 },
    sgpaHist: [8.3, 8.5, 8.6, 8.7, 8.7, 8.8, 8.9, 9.0],
    notifications: []
  },
  {
    id: 17,
    usn: "1SG22CS124",
    name: "Deepa",
    email: "Deepa@student.edu",
    password: "student123",
    phone: "9876543217",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "DevOps",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 7.7,
    cgpa: 7.5,
    backlogs: 1,
    status: "approved",
    teacherId: 5,
    attendance: { "Database Management System": 76, "DBMS Lab": 70 },
    sgpaHist: [7.0, 7.2, 7.3, 7.4, 7.4, 7.5, 7.6, 7.7],
    notifications: [
      { id: 1, msg: "DBMS Lab attendance below 75% — warning issued", type: "warn", read: false, date: "Dec 03" }
    ]
  },
  {
    id: 18,
    usn: "1SG22CS125",
    name: "Rachita",
    email: "Rachita@student.edu",
    password: "student123",
    phone: "9876543218",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "IoT",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.5,
    cgpa: 8.3,
    backlogs: 0,
    status: "approved",
    teacherId: 5,
    attendance: { "Database Management System": 88, "DBMS Lab": 85 },
    sgpaHist: [7.8, 8.0, 8.1, 8.2, 8.2, 8.3, 8.4, 8.5],
    notifications: []
  },
  {
    id: 19,
    usn: "1SG22CS126",
    name: "Vishwa",
    email: "vishwa@student.edu",
    password: "student123",
    phone: "9876543219",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Machine Learning",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 8.8,
    cgpa: 8.6,
    backlogs: 0,
    status: "approved",
    teacherId: 5,
    attendance: { "Database Management System": 90, "DBMS Lab": 87 },
    sgpaHist: [8.1, 8.3, 8.4, 8.5, 8.5, 8.6, 8.7, 8.8],
    notifications: []
  },
  {
    id: 20,
    usn: "1SG22CS127",
    name: "Rukmini",
    email: "Rukmini@student.edu",
    password: "student123",
    phone: "9876543220",
    university: "VTU",
    college: "SCE",
    branch: "CSE",
    specialization: "Blockchain",
    section: "B",
    semester: 8,
    year: 4,
    sgpa: 7.3,
    cgpa: 7.1,
    backlogs: 2,
    status: "approved",
    teacherId: 5,
    attendance: { "Database Management System": 65, "DBMS Lab": 60 },
    sgpaHist: [6.5, 6.7, 6.8, 6.9, 7.0, 7.0, 7.1, 7.3],
    notifications: [
      { id: 1, msg: "Multiple subjects below 75% attendance — urgent action required", type: "danger", read: false, date: "Dec 02" }
    ]
  },
];

export const INIT_ASSIGNMENTS = [
  {
    id: 1,
    title: "CN Subnetting Exercise",
    subject: "Computer Networks",
    teacherId: 1,
    branch: "CSE",
    dueDate: "2024-12-15",
    desc: "Solve 10 subnetting problems using VLSM. Show all working including subnet mask, network address, broadcast address and host range.",
    status: "active",
    submissions: [
      { studentId: 1, studentName: "Sudarshan", submittedAt: "2024-12-14", content: "All 10 subnetting problems solved with detailed working", status: "reviewed", grade: "A" }
    ]
  },
  {
    id: 2,
    title: "CN Lab - Packet Tracer Network Setup",
    subject: "Computer Networks Lab",
    teacherId: 1,
    branch: "CSE",
    dueDate: "2024-12-18",
    desc: "Configure a small office network in Cisco Packet Tracer with 3 routers, 2 switches and 10 PCs. Enable OSPF routing and verify connectivity.",
    status: "active",
    submissions: [
      { studentId: 2, studentName: "Srujan", submittedAt: "2024-12-17", content: "Network configured with OSPF routing and full connectivity verified", status: "submitted", grade: null }
    ]
  },
  {
    id: 3,
    title: "SDLC Case Study Report",
    subject: "Software Development Life Cycle",
    teacherId: 2,
    branch: "CSE",
    dueDate: "2024-12-20",
    desc: "Choose any real-world software project and map its development to one of the SDLC models (Agile/Waterfall/Spiral). Write a 5-page report with diagrams.",
    status: "active",
    submissions: []
  },
  {
    id: 4,
    title: "AI Search Algorithms Implementation",
    subject: "Artificial Intelligence",
    teacherId: 3,
    branch: "CSE",
    dueDate: "2024-12-22",
    desc: "Implement BFS, DFS, A* and Hill Climbing search algorithms in Python. Compare performance on the 8-puzzle problem with time and space complexity analysis.",
    status: "active",
    submissions: [
      { studentId: 12, studentName: "Spoorthi", submittedAt: "2024-12-20", content: "All 4 algorithms implemented with performance comparison table", status: "submitted", grade: null }
    ]
  },
  {
    id: 5,
    title: "Parallel Computing - MPI Matrix Multiplication",
    subject: "Parallel Computing",
    teacherId: 4,
    branch: "CSE",
    dueDate: "2024-12-24",
    desc: "Write an MPI program to perform parallel matrix multiplication. Compare execution time with serial version for matrices of size 100x100, 500x500 and 1000x1000.",
    status: "active",
    submissions: []
  },
  {
    id: 6,
    title: "DBMS ER Diagram and Normalization",
    subject: "Database Management System",
    teacherId: 5,
    branch: "CSE",
    dueDate: "2024-12-19",
    desc: "Design an ER diagram for a University Management System and convert it to a normalized relational schema up to 3NF. Include at least 8 entities with proper constraints.",
    status: "active",
    submissions: [
      { studentId: 16, studentName: "Shreya", submittedAt: "2024-12-18", content: "Complete ER diagram with 10 entities normalized to 3NF with all constraints defined", status: "reviewed", grade: "A" }
    ]
  },
  {
    id: 7,
    title: "DBMS Lab - SQL Query Practice",
    subject: "DBMS Lab",
    teacherId: 5,
    branch: "CSE",
    dueDate: "2024-12-21",
    desc: "Write SQL queries for the University schema covering DDL, DML, all types of joins, subqueries, views, triggers and stored procedures. Minimum 25 queries required.",
    status: "active",
    submissions: []
  },
];